sudo : required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t okdori/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true okdori/react-docker npm run test -- --coverage

after_success:
  - echo "Test success!!!"